# Generated by Django 4.1.5 on 2023-02-09 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0003_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="photo",
            field=models.ImageField(blank=True, upload_to="media/images/"),
        ),
    ]
